
version: '3.8'

services:
  db:
    container_name: social_mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - dbsocial:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DB_NAME}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306

  adminer:
    container_name: social_adminer
    restart: unless-stopped
    image: adminer:latest
    ports:
      - 8082:8080
    depends_on:
      - db

  redis:
    container_name: social_redis
    restart: unless-stopped
    image: redis:6-alpine
    volumes:
      - redis_volume:/data

  social_app:
    container_name: social_app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9228:9228
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  dbsocial:
    driver: local
  redis_volume:
